const animalJokes = [
    "Why don't sharks like fast food? Because they can't catch it!",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the cow become an astronaut? It wanted to go to the moooon!",
    "How do you catch a squirrel? Climb up a tree and act like a nut!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What do you call a pig that knows karate? A pork chop!",
    "Why did the horse sit down at the table? It wanted to be a stable genius.",
    "What do you get when you cross a snake and a pie? A python.",
    "Why do hummingbirds hum? Because they don't know the words!",
    "What's a cat's favorite color? Purr-ple!",
    "What do you call a cold dog? A chili dog!",
    "How does a farmer count cows? With a cowculator.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the spider break up with his girlfriend? She found out he was a web designer.",
    "What's a frog's favorite candy? Lollihops!",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the cow become an astronaut? It wanted to go to the moooon!",
    "How do you catch a squirrel? Climb up a tree and act like a nut!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What do you call a pig that knows karate? A pork chop!",
    "Why did the horse sit down at the table? It wanted to be a stable genius.",
    "What do you get when you cross a snake and a pie? A python.",
    "Why do hummingbirds hum? Because they don't know the words!",
    "What's a cat's favorite color? Purr-ple!",
    "What do you call a cold dog? A chili dog!",
    "How does a farmer count cows? With a cowculator.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the spider break up with his girlfriend? She found out he was a web designer.",
    "What's a frog's favorite candy? Lollihops!",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the cow become an astronaut? It wanted to go to the moooon!",
    "How do you catch a squirrel? Climb up a tree and act like a nut!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What do you call a pig that knows karate? A pork chop!",
    "Why did the horse sit down at the table? It wanted to be a stable genius.",
    "What do you get when you cross a snake and a pie? A python.",
    "Why do hummingbirds hum? Because they don't know the words!",
    "What's a cat's favorite color? Purr-ple!",
    "What do you call a cold dog? A chili dog!",
    "How does a farmer count cows? With a cowculator.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the spider break up with his girlfriend? She found out he was a web designer.",
    "What's a frog's favorite candy? Lollihops!",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the cow become an astronaut? It wanted to go to the moooon!",
    "How do you catch a squirrel? Climb up a tree and act like a nut!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What do you call a pig that knows karate? A pork chop!",
    "Why did the horse sit down at the table? It wanted to be a stable genius.",
    "What do you get when you cross a snake and a pie? A python.",
    "Why do hummingbirds hum? Because they don't know the words!",
    "What's a cat's favorite color? Purr-ple!",
    "What do you call a cold dog? A chili dog!",
    "How does a farmer count cows? With a cowculator.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the spider break up with his girlfriend? She found out he was a web designer.",
    "What's a frog's favorite candy? Lollihops!",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the cow become an astronaut? It wanted to go to the moooon!",
    "How do you catch a squirrel? Climb up a tree and act like a nut!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What do you call a pig that knows karate? A pork chop!",
    "Why did the horse sit down at the table? It wanted to be a stable genius.",
    "What do you get when you cross a snake and a pie? A python.",
    "Why do hummingbirds hum? Because they don't know the words!",
    "What's a cat's favorite color? Purr-ple!",
    "What do you call a cold dog? A chili dog!",
    "How does a farmer count cows? With a cowculator.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the spider break up with his girlfriend? She found out he was a web designer.",
    "What's a frog's favorite candy? Lollihops!"
  ];
  
  module.exports = animalJokes;
  