const medicalJokes = [
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "Why did the nurse carry a red pen? To draw blood!",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a dentist and a New York Yankee? One drills for oil, the other for gold.",
    "Why did the doctor carry a red pen? In case they needed to draw blood.",
    "What's the difference between a doctor and a plumber? A doctor washes his hands after he goes to the bathroom, a plumber washes his hands before he goes to the bathroom!",
    "Why did the scarecrow become a successful doctor? Because he was outstanding in his field!",
  ];
  
  module.exports = medicalJokes;
  