const programmingJokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem!",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do Java developers wear glasses? Because they can't C#.",
    "Why do Python programmers prefer cold weather? Because they like to use PyCharm.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why don't programmers like to play hide and seek? Because good programmers are always visible.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the programmer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
  ];
  
  module.exports = programmingJokes;
  