const scienceJokes = [
    "Why was the math book sad? It had too many problems.",
    "What do you call an educated tube? A graduated cylinder.",
    "Why can't you trust an atom? Because they make up everything.",
    "Did you hear oxygen went on a date with potassium? It went OK.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What do you call a microbiologist who has traveled to every country in the world? A man of many cultures.",
    "Why did the biologist break up with the psychologist? They had different cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the physics book afraid to go to school? It had too many problems.",
    "Why are chemists great at solving problems? They have all the solutions.",
    "Why do chemists like nitrates so much? They're cheaper than day rates.",
    "Why did the white blood cell cross the road? It wanted to get to the other side.",
    "What's the fastest way to send a chemistry joke? By methylated.",
    "Why did the tectonic plate break up with the volcano? He thought he was too hot-headed.",
    "What do you get when you mix sulfur, tungsten, and silver? SWAg.",
    "Why do biologists enjoy lightning storms? They have flashbacks.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the math book sad? It had too many problems.",
    "What do you call an educated tube? A graduated cylinder.",
    "Why can't you trust an atom? Because they make up everything.",
    "Did you hear oxygen went on a date with potassium? It went OK.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What do you call a microbiologist who has traveled to every country in the world? A man of many cultures.",
    "Why did the biologist break up with the psychologist? They had different cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the physics book afraid to go to school? It had too many problems.",
    "Why are chemists great at solving problems? They have all the solutions.",
    "Why do chemists like nitrates so much? They're cheaper than day rates.",
    "Why did the white blood cell cross the road? It wanted to get to the other side.",
    "What's the fastest way to send a chemistry joke? By methylated.",
    "Why did the tectonic plate break up with the volcano? He thought he was too hot-headed.",
    "What do you get when you mix sulfur, tungsten, and silver? SWAg.",
    "Why do biologists enjoy lightning storms? They have flashbacks.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the math book sad? It had too many problems.",
    "What do you call an educated tube? A graduated cylinder.",
    "Why can't you trust an atom? Because they make up everything.",
    "Did you hear oxygen went on a date with potassium? It went OK.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What do you call a microbiologist who has traveled to every country in the world? A man of many cultures.",
    "Why did the biologist break up with the psychologist? They had different cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the physics book afraid to go to school? It had too many problems.",
    "Why are chemists great at solving problems? They have all the solutions.",
    "Why do chemists like nitrates so much? They're cheaper than day rates.",
    "Why did the white blood cell cross the road? It wanted to get to the other side.",
    "What's the fastest way to send a chemistry joke? By methylated.",
    "Why did the tectonic plate break up with the volcano? He thought he was too hot-headed.",
    "What do you get when you mix sulfur, tungsten, and silver? SWAg.",
    "Why do biologists enjoy lightning storms? They have flashbacks.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the math book sad? It had too many problems.",
    "What do you call an educated tube? A graduated cylinder.",
    "Why can't you trust an atom? Because they make up everything.",
    "Did you hear oxygen went on a date with potassium? It went OK.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What do you call a microbiologist who has traveled to every country in the world? A man of many cultures.",
    "Why did the biologist break up with the psychologist? They had different cells.",
    "What did the biologist wear to impress? Designer genes.",
    "Why was the physics book afraid to go to school? It had too many problems.",
    "Why are chemists great at solving problems? They have all the solutions.",
    "Why do chemists like nitrates so much? They're cheaper than day rates.",
    "Why did the white blood cell cross the road? It wanted to get to the other side.",
    "What's the fastest way to send a chemistry joke? By methylated.",
    "Why did the tectonic plate break up with the volcano? He thought he was too hot-headed.",
    "What do you get when you mix sulfur, tungsten, and silver? SWAg.",
    "Why do biologists enjoy lightning storms? They have flashbacks.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why do biologists like to have greenhouse parties? They always have great cells.",
    "What did the biologist wear to impress? Designer genes.",
  ];
  
  module.exports = scienceJokes;
  