const sportsJokes = [
    "Why did the basketball player bring a ladder to the game? Because they heard the Knicks were good at rebounds!",
    "Why did the football coach go to the bank? To get his quarterback!",
    "Why did the golfer bring an extra pair of pants? In case he got a hole-in-one!",
    "What did the football coach say to the vending machine? Give me my quarterback!",
    "Why did the soccer ball go to school? To get better at kicking!",
    "Why was the baseball team always in trouble? They couldn't stop making pitches!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
    "Why did the soccer player bring string to the game? In case they needed to tie the score!",
    "Why did the basketball team go to the bank? To get their bounce back!",
    "What's the difference between a tennis player and a swimmer? A tennis player has a net and a swimmer has a stroke!",
  ];
  
  module.exports = sportsJokes;
  